language: php

php: 7.1

branches:
    only:
        - master

install:
    - composer install
    - npm install

script:
    - npm run build

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: dist
    on:
        branch: master

notifications:
    email: false
